FROM rust:1.82-slim

# Устанавливаем необходимые зависимости для компиляции
RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем целевую платформу
RUN rustup target add x86_64-unknown-linux-gnu

# Создаем рабочую директорию
WORKDIR /app

# Копируем файлы проекта
COPY . .

# Собираем проект
RUN cargo build --release --target x86_64-unknown-linux-gnu

# Команда по умолчанию - копирование результата
CMD ["cp", "/app/target/x86_64-unknown-linux-gnu/release/happytest", "/output/"]
