{{- if and .Values.s3.enabled (not .Values.aws.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "happytest-reader.fullname" . }}-aws
  labels:
    {{- include "happytest-reader.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.aws.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | quote }}
  {{- end }}
  {{- if .Values.aws.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | quote }}
  {{- end }}
  S3_BUCKET: {{ .Values.s3.bucket | quote }}
{{- end }}
