---
- name: Ensure logs directory exists
  file:
    path: "{{ reader_base_path }}/logs"
    state: directory
    owner: "{{ reader_user }}"
    group: "{{ reader_group }}"
    mode: '0755'

- name: Create cron jobs for trading pairs
  cron:
    name: "HappyTest {{ item }} reader"
    user: "{{ reader_user }}"
    minute: "*/59"
    job: "{{ reader_base_path }}/bin/reader --output /Users/banka/data --symbol {{ item }} --duration {{ collection_interval }} >> {{ reader_base_path }}/logs/reader_{{ item | lower }}.log 2>&1"
    state: present
  loop: "{{ trading_pairs }}"
  when: trading_pairs is defined
